"""
Django settings for AstroProje project.

Generated by 'django-admin startproject' using Django 5.2.1.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-p-1ba6ki+$vmv7j9^s4bjv%$$s0w$2=typ78zcgw#1f#!3gg9="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Jazzmin admin teması
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Üçüncü parti uygulamalar
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',  # Filtreleme için eklendi
    
    # Proje uygulamaları
    'astro_core',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

JAZZMIN_SETTINGS = {
    # başlık
    "site_title": "AstroEşleşme Admin",
    "site_header": "AstroEşleşme",
    "site_brand": "AstroEşleşme",
    "site_logo": "images/logo.png",
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    # Renkler ve temalar
    "welcome_sign": "AstroEşleşme Yönetim Paneline Hoş Geldiniz",
    "copyright": "AstroEşleşme Ltd",
    "search_model": ["auth.User", "astro_core.AstrologicalSystem"],
    "user_avatar": None,
    # Stil
    "topmenu_links": [
        {"name": "Ana Sayfa", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Site", "url": "/", "new_window": True},
        {"name": "API", "url": "/api/", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "Destek", "url": "https://github.com/erkanozturk1903/AstroEslesmeProjesi/issues", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "auth",
        "astro_core.UserProfile",
        # Astroloji modelleri
        "astro_core.AstrologicalSystem",
        "astro_core.Sign", 
        "astro_core.Planet", 
        "astro_core.House", 
        "astro_core.Aspect", 
        "astro_core.PlanetInSign", 
        "astro_core.PlanetInHouse", 
        "astro_core.PlanetAspect", 
        "astro_core.BirthChart",
        # Tarot modelleri
        "astro_core.TarotDeck", 
        "astro_core.TarotCard", 
        "astro_core.TarotSpread", 
        "astro_core.TarotReading",
        # Numeroloji modelleri
        "astro_core.NumberMeaning", 
        "astro_core.NumerologyProfile", 
        "astro_core.LifePathNumber",
        # Uyumluluk modelleri 
        "astro_core.CompatibilityScore",
    ],
    "custom_links": {
        "astro_core": [{
            "name": "Doğum Haritası Hesaplama",
            "url": "admin:astro_core_birthchart_changelist",
            "icon": "fas fa-chart-pie",
        }]
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "astro_core.AstrologicalSystem": "fas fa-globe-americas",
        "astro_core.Sign": "fas fa-star",
        "astro_core.Planet": "fas fa-sun",
        "astro_core.House": "fas fa-home",
        "astro_core.Aspect": "fas fa-project-diagram",
        "astro_core.PlanetInSign": "fas fa-map-marker-alt",
        "astro_core.PlanetInHouse": "fas fa-map-pin",
        "astro_core.PlanetAspect": "fas fa-link",
        "astro_core.BirthChart": "fas fa-birthday-cake",
        "astro_core.UserProfile": "fas fa-id-card",
        "astro_core.TarotDeck": "fas fa-clone",
        "astro_core.TarotCard": "fas fa-credit-card",
        "astro_core.TarotSpread": "fas fa-th-large",
        "astro_core.TarotReading": "fas fa-book-open",
        "astro_core.NumberMeaning": "fas fa-hashtag",
        "astro_core.NumerologyProfile": "fas fa-calculator",
        "astro_core.CompatibilityScore": "fas fa-heart",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Dashboard'daki widget'lar/kartlar için ayarlar
    "show_counts": True,  # Model kayıt sayılarını göster
    "show_chart": True,  # İstatistik grafiklerini göster
    "dashboard_list_display": {
        # Her modelin dashboard üzerinde nasıl gösterileceğini özelleştir
        "auth.user": ["username", "email", "date_joined"],
        "astro_core.AstrologicalSystem": ["name"],
        "astro_core.Sign": ["name", "element", "modality"],
        "astro_core.Planet": ["name"],
    },
    # Dashboard için renk paletleri
    "changeform_format": "collapsible",
    "dashboards": {
        "main": {
            "title": "Ana Dashboard",
            "order": 0,
            "description": "AstroEşleşme yönetim merkezi",
        },
        "astro": {
            "title": "Astroloji Verileri",
            "order": 1,
            "description": "Astroloji ile ilgili tüm veriler",
            "models": [
                "astro_core.AstrologicalSystem", 
                "astro_core.Sign", 
                "astro_core.Planet",
                "astro_core.House",
                "astro_core.Aspect",
            ],
        },
        "tarot": {
            "title": "Tarot Verileri",
            "order": 2,
            "description": "Tarot ile ilgili tüm veriler",
            "models": [
                "astro_core.TarotDeck", 
                "astro_core.TarotCard", 
                "astro_core.TarotSpread", 
                "astro_core.TarotReading",
            ],
        },
        "numerology": {
            "title": "Numeroloji Verileri",
            "order": 3,
            "description": "Numeroloji ile ilgili tüm veriler",
            "models": [
                "astro_core.NumberMeaning", 
                "astro_core.NumerologyProfile", 
                "astro_core.LifePathNumber",
            ],
        },
    },
     "custom_css": "css/custom_admin.css",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",  # Daha canlı renk için primary
    "accent": "accent-primary",  # İkinci görseldeki gibi canlı aksan rengi
    "navbar": "navbar-dark",
    "no_navbar_border": True,  # Daha modern görünüm için sınır kaldırıldı
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",  # Canlı ana renkle eşleşen sidebar
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",  # İkinci görseldeki canlı renkli kartlar için default tema
    "dark_mode_theme": None,  # Karanlık mod kapatıldı
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True
}

ROOT_URLCONF = "AstroProje.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],  # Template dizini eklendi
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",  # Media için eklendi
            ],
        },
    },
]

WSGI_APPLICATION = "AstroProje.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "tr-tr"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Statik dosyalar için eklendi

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# X-Frame-Options
X_FRAME_OPTIONS = 'SAMEORIGIN'  # Admin panelindeki "Popup" özelliği için eklendi